name: test1
on: push

jobs:
  build-on-ubuntu:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Установить Vagrant на macOS runner
      - name: Install Vagrant
        run: |
          brew install --cask vagrant
          vagrant --version

      # 2. Запуск Vagrant уже напрямую, без github-actions-vagrant
      - name: Run Zabbix tests in VMs
        run: |
          cd "$GITHUB_WORKSPACE"
            vagrant up vm1-test vm3-test
            vagrant ssh vm1-test -c "cd /vagrant && ./monitor/zabbix/test_zabbix.sh"
